version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
      - ./custom.cnf:/etc/mysql/conf.d/custom.cnf
    ports:
      - "3306:3306"